### ISSUE TITLE
License terms?

### ISSUE THREAD

**Issue by glutanimate** [ijanos/ragtag#1]
Hi there,

thanks a lot for sharing this project. It has been very helpful in learning how to construct a simple thumbnail grid in Qt.

I'm filing this report because I was planning on using some of your widgets in a project of mine if that's fine with you. Which license could I assume in that case?

Thanks again in advance!

**Comment by ijanos** [comment]
Hello there, what would you prefer? :) 

I guess I will Apache/MIT dual-license as that is the most permissive I can think of. However the code is importing PyQt4 which is GPL licensed so maybe I'm required to use GPL, I'm not sure.

**Comment by glutanimate** [comment]
Thanks for the swift response! The project I'm working on will probably have to be licensed under the GPL anyway, so I'd be more than happy with any of these options :).

**Comment by ijanos** [comment]
Be sure to post a link if you created something :) good luck!

**Comment by glutanimate** [comment]
Will do! Thanks!
